language: swift
osx_image: xcode9.3
# xcode_project: HumanReadableTimeTDDKata.xcodeproj # path to your xcodeproj folder
# xcode_scheme: HumanReadableTimeTDDKata
# xcode_sdk: iphonesimulator11.3
script: xcodebuild -project HumanReadableTimeTDDKata.xcodeproj -scheme HumanReadableTimeTDDKata -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
